apiVersion: v1
kind: Namespace
metadata:
  name: staging
  labels:
    toolkit.fluxcd.io/tenant: dev-team
---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    toolkit.fluxcd.io/tenant: dev-team
  name: flux-apps
  namespace: staging
