apiVersion: v1
kind: Namespace
metadata:
  name: staging
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-sync
  namespace: staging
spec:
  interval: 1h
  retryInterval: 3m
  timeout: 5m
  prune: true
  wait: true
  path: ./clusters/staging
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  kubeConfig:
    secretRef:
      name: cluster-kubeconfig
